# Generated by Django 5.2.4 on 2025-07-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Not Assigned', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(default='Not Assigned', max_length=100),
            preserve_default=False,
        ),
    ]
