# Generated by Django 5.2.4 on 2025-07-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('3pm_to_12am', '3 PM to 12 AM'), ('4pm_to_1am', '4 PM to 1 AM'), ('8am_to_5pm', '8 AM to 5 PM'), ('9am_to_6pm', '9 AM to 6 PM')], default='8am_to_5pm', max_length=100),
        ),
    ]
