# Generated by Django 5.2.4 on 2025-07-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_employee_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('3pm_to_12am', '3 PM to 12 AM'), ('4pm_to_1am', '4 PM to 1 AM'), ('8pm_to_5am', '8 PM to 5 AM'), ('9pm_to_6am', '9 PM to 6 AM')], default='8am_to_5pm', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='Designation',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Employee', max_length=100),
        ),
    ]
