# Generated by Django 5.2.4 on 2025-07-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_employee_designation_alter_employee_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('3pm_to_12am', '3 PM to 12 AM'), ('4pm_to_1am', '4 PM to 1 AM'), ('8pm_to_5am', '8 PM to 5 AM'), ('9pm_to_6am', '9 PM to 6 AM')], default='8pm_to_5am', max_length=100),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
        ),
    ]