# Generated by Django 5.2.4 on 2025-07-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_date_break'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('3pm_to_12am', '3 PM to 12 AM'), ('4pm_to_1am', '4 PM to 1 AM'), ('5pm_to_2am', '5 PM to 2 AM'), ('6pm_to_3am', '6 PM to 3 AM'), ('7pm_to_4am', '7 PM to 4 AM'), ('8pm_to_5am', '8 PM to 5 AM'), ('9pm_to_6am', '9 PM to 6 AM'), ('10pm_to_7am', '10 PM to 7 AM'), ('12am_to_9am', '12 AM to 9 AM'), ('1am_to_10am', '1 AM to 10 AM')], default='8pm_to_5am', max_length=100),
        ),
    ]
