# Generated by Django 5.2.4 on 2025-07-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
