# Generated by Django 5.2.4 on 2025-07-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('On Time', 'On Time'), ('Late', 'Late')], default='On Time', max_length=10),
        ),
    ]
