# Generated by Django 5.2.4 on 2025-07-28 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='date_requested',
        ),
        migrations.AddField(
            model_name='leave',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
