# Generated by Django 5.2.4 on 2025-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_rename_designation_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Senior Developer', 'Senior Developer'), ('Admin', 'Admin'), ('Manager', 'Manager')], default='Junior Developer', max_length=100),
        ),
    ]
