# Generated by Django 5.2.4 on 2025-07-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Hr', 'Hr'), ('Admin', 'Admin')], default='Employee', max_length=100),
        ),
    ]
