# Generated by Django 5.2.4 on 2025-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], max_length=10, null=True),
        ),
    ]
