# Generated by Django 5.2.4 on 2025-07-31 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_remove_leave_timestamp_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Emergency Leave', 'Emergency Leave'), ('Casual Leave', 'Casual Leave'), ('Annual Leave', 'Annual Leave')], default='Casual Leave', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Upsell', 'Upsell'), ('Front', 'Front'), ('Admin', 'Admin'), ('Book', 'Book'), ('Marketing', 'Marketing'), ('Hr', 'Hr'), ('Development', 'Development'), ('R&D', 'R&D'), ('Design', 'Design')], default='Design', max_length=100),
        ),
    ]
