# Generated by Django 5.2.4 on 2025-07-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_leave_leave_type_alter_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Emergency Leave', 'Emergency Leave'), ('Vacation Leave', 'Vacation Leave'), ('Personal Leave', 'Personal Leave')], default='Personal Leave', max_length=50),
        ),
    ]
