# Generated by Django 5.2.4 on 2025-08-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_attendance_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_leave_balance',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_leave_balance',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacation_leave_balance',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
