# Generated by Django 5.2.4 on 2025-08-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_employee_emergency_leave_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emergency_leave_balance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='personal_leave_balance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sick_leave_balance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vacation_leave_balance',
        ),
    ]
