# Generated by Django 5.2.4 on 2025-08-18 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_leave', models.IntegerField(default=8)),
                ('emergency_leave', models.IntegerField(default=8)),
                ('vacation_leave', models.IntegerField(default=8)),
                ('personal_leave', models.IntegerField(default=8)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
        ),
    ]
