# Generated by Django 5.2.4 on 2025-08-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_leavebalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
