# Generated by Django 5.2.4 on 2025-08-18 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_delete_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Emergency Leave', 'Emergency Leave'), ('Vacation Leave', 'Vacation Leave'), ('Personal Leave', 'Personal Leave')], max_length=50)),
                ('balance', models.PositiveIntegerField(default=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
