# Generated by Django 5.2.4 on 2025-08-26 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter a valid email address', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
