# Generated by Django 5.2.4 on 2025-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
