# Generated by Django 5.2.4 on 2025-08-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_employee_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='DOB',
            new_name='birthday',
        ),
    ]
