# Generated by Django 5.2.4 on 2025-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_rename_dob_employee_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AddField(
            model_name='employee',
            name='Department',
            field=models.CharField(choices=[('Upsell', 'Upsell'), ('Front', 'Front'), ('Admin', 'Admin'), ('Book', 'Book'), ('Marketing', 'Marketing'), ('Hr', 'Hr'), ('Development', 'Development'), ('R&D', 'R&D'), ('Design', 'Design')], default='Design', max_length=100),
        ),
    ]
