# Generated by Django 5.2.4 on 2025-08-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_remove_employee_designation_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Department',
            new_name='department',
        ),
    ]
