# Generated by Django 5.2.4 on 2025-08-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_rename_department_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='designation',
        ),
    ]
