# Generated by Django 5.2.4 on 2025-08-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_rename_department_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='weekend_days',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more days as weekend'),
        ),
    ]
