# Generated by Django 5.2.4 on 2025-08-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_employee_weekend_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='weekend_days',
        ),
    ]
