# Generated by Django 5.2.4 on 2025-08-29 21:06

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_remove_employee_weekend_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='weekend',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=['Saturday', 'Sunday'], help_text='Select weekend days for this employee', max_length=56),
        ),
    ]
