# Generated by Django 5.2.4 on 2025-08-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_employee_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Weekend', 'Weekend')], max_length=10, null=True),
        ),
    ]
