# Generated by Django 5.2.4 on 2025-09-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_office_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_working_hour',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Upsell', 'Upsell'), ('Front', 'Front'), ('Admin', 'Admin'), ('Book', 'Book'), ('Marketing', 'Marketing'), ('Hr', 'Hr'), ('Development', 'Development'), ('R&D', 'R&D'), ('Design', 'Design')], default='Design', max_length=100, verbose_name='Department'),
        ),
    ]
