# Generated by Django 5.2.4 on 2025-09-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_attendance_total_office_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_break_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
