# Generated by Django 5.2.4 on 2025-09-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_meeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
