# Generated by Django 5.2.4 on 2025-09-02 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0040_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='The employee who started the meeting (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
    ]
