# Generated by Django 5.2.4 on 2025-09-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0041_alter_meeting_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='end_time',
            new_name='ended_at',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='start_time',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='status',
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
