# Generated by Django 5.2.4 on 2025-09-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0043_remove_meeting_name_meeting_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='employee',
        ),
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
