# Generated by Django 5.2.4 on 2025-09-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0044_remove_meeting_employee_meeting_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='name',
        ),
        migrations.AddField(
            model_name='meeting',
            name='employee',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='attendance.employee'),
            preserve_default=False,
        ),
    ]
