# Generated by Django 5.2.4 on 2025-09-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0045_remove_meeting_name_meeting_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
