# Generated by Django 5.2.4 on 2025-09-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0046_meeting_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('Upsell', 'Upsell'), ('Front', 'Front'), ('Admin', 'Admin'), ('Book', 'Book'), ('Marketing', 'Marketing'), ('Hr', 'Hr'), ('Development', 'Development'), ('R&D', 'R&D'), ('Design', 'Design')], max_length=100, null=True, verbose_name='Department'),
        ),
    ]
