# Generated by Django 5.2.4 on 2025-09-10 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0048_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='balance',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_type',
        ),
    ]
