# Generated by Django 5.2.4 on 2025-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0049_alter_leavebalance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='balance',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='total_balance',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
