# Generated by Django 5.2.4 on 2025-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0052_employee_id_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
