# Generated by Django 5.2.4 on 2025-09-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0053_leave_seen_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, help_text='Enter employee position (e.g., Junior Developer, Senior Developer, Manager)', max_length=100, null=True),
        ),
    ]
