# Generated by Django 5.2.4 on 2025-09-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0054_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('Upsell', 'Upsell'), ('Front', 'Front'), ('Admin', 'Admin'), ('Book', 'Book'), ('Marketing', 'Marketing'), ('HR', 'HR'), ('Development', 'Development'), ('R&D', 'R&D'), ('Design', 'Design'), ('Production', 'Production')], max_length=100, null=True, verbose_name='Department'),
        ),
    ]
