# Generated by Django 5.2.4 on 2025-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0055_alter_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
